# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

replicaCount: 1

image:
  tag: 27

agent:
  prometheus:
    tag: 12
  otel:
    tag: 1